### ISSUE TITLE
Export Mod Problem

### ISSUE THREAD

**Issue by Amospher** [SpectrumQT/WWMI-TOOLS#3]
Hello!Thank you very much for your code. I‘m new to modding, I've encountered an issue when attempting to export my mod files. The error message I received is as follows:

`Python: Traceback (most recent call last):
  File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\WWMI-Tools\wwmi_tools.py", line 410, in execute
    blender_export(self, context, cfg, data_map)
  File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\WWMI-Tools\blender_export\blender_export.py", line 322, in blender_export
    object_merger = ObjectMerger(
  File "<string>", line 10, in __init__
  File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\WWMI-Tools\blender_export\object_merger.py", line 70, in __post_init__
    self.initialize_components()
  File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\WWMI-Tools\blender_export\object_merger.py", line 80, in initialize_components
    for component_id, component in enumerate(self.extracted_object.components): 
AttributeError: 'NoneType' object has no attribute 'components'`

I would greatly appreciate any assistance or guidance you could provide to resolve this issue. Thank you!

**Comment by SpectrumQT** [comment]
Hello! It looks like you've just specified incorrect path to Object Sources folder (must be hash-named folder with Metadata.json inside.
